### ISSUE TITLE
Enhancements for Webhook

### ISSUE THREAD

**Issue by werner33** [werner33/freeCodeCamp#2]
The webhook is working as expected! Looks great. 

There are four enhancements that need to be made. I've demoed them in [this video](https://www.loom.com/share/093515cadf014a8787319adc4cea5908?sid=c25c1246-0706-4b5b-bc6f-e204be2fecce):

1. On successful save, update or delete of the webhook, the ui should immediately reflect the change. Right now the change is not reflected until the page is refreshed.

2. There should be a second field added to the webhook from for a secret. This should be optional. The allows the consumer to provide a unique secret per user to confirm that the webhook is coming from a specific person. 
You can look at this same type of feature here on Codewars: 
<img width="800" alt="Screen Shot 2024-01-11 at 12 20 58 AM" src="https://github.com/werner33/freeCodeCamp/assets/692461/ab1e5bab-e5d8-477a-aed7-d1b159483f75">

3. An initial event should be emitted when a webhook is added or updated. It should look like this:

`
  {
    username: 'certifieduser',
    secret: 'some_secret',
    eventType: 'webhook_added'
  }
`
This allows the receiver to confirm to the sender that the webhook was configured properly.

4. Add the same text that Codewars has on their form: 'Optionally be notified of events.' above the New Webhook label.

Let me know if you have any questions. Thank you.

**Comment by SajeevPaul** [comment]
@werner33  - I have fixed the issue and pushed changes into the main branch. Can you review and give me your feedback?

**Comment by werner33** [comment]
Looks good for the most part. 

Can you change the design of the UI for an existing webhook to something just like this:

<img width="883" alt="Screen Shot 2024-01-22 at 3 34 53 PM" src="https://github.com/werner33/freeCodeCamp/assets/692461/bfc0c291-8759-4160-8de5-1a7515ca500e">

Thank you!
